# Generated by Django 3.0.3 on 2020-02-19 22:29
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181016_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googletrendsatom',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Google Trends'},
        ),
        migrations.RenameField(
            model_name='googletrendsatom',
            old_name='updated',
            new_name='published',
        ),
        migrations.AddField(
            model_name='googletrendsatom',
            name='snippet',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
