# Generated by Django 3.0.3 on 2020-02-19 22:17
# pylint: disable

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181016_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrendsatom',
            name='snippet',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
